/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/oABiyeWN8CC7OTzx/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#74757a"]} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <group name="Bunny Cube" position={[437.81, 303.93, 878.33]}>
            <mesh
              name="Rectangle 9"
              geometry={nodes["Rectangle 9"].geometry}
              material={materials.pink}
              castShadow
              receiveShadow
              position={[21.58, 87.01, 7.15]}
              rotation={[0, 0, -0.17]}
              scale={1}
            />
            <mesh
              name="Rectangle 6"
              geometry={nodes["Rectangle 6"].geometry}
              material={materials.pink}
              castShadow
              receiveShadow
              position={[-20.89, 89.75, 7.15]}
            />
            <mesh
              name="Cube 6"
              geometry={nodes["Cube 6"].geometry}
              material={materials.pink}
              castShadow
              receiveShadow
              position={[33.67, 33.29, 28.45]}
            />
            <mesh
              name="Cube 12"
              geometry={nodes["Cube 12"].geometry}
              material={materials["white-2"]}
              castShadow
              receiveShadow
              position={[25.45, 3.43, -29.06]}
              scale={[1.23, 1, 1.44]}
            />
            <mesh
              name="Cube 121"
              geometry={nodes["Cube 121"].geometry}
              material={materials["white-2"]}
              castShadow
              receiveShadow
              position={[-26.87, 3.43, -29.06]}
              scale={[1.23, 1, 1.44]}
            />
            <mesh
              name="Cube 8"
              geometry={nodes["Cube 8"].geometry}
              material={materials["white-2"]}
              castShadow
              receiveShadow
              position={[25.45, 3.43, 18.02]}
              scale={[1.23, 1, 1.44]}
            />
            <mesh
              name="Cube 7"
              geometry={nodes["Cube 7"].geometry}
              material={materials["white-2"]}
              castShadow
              receiveShadow
              position={[-26.87, 3.43, 18.02]}
              scale={[1.23, 1, 1.44]}
            />
            <mesh
              name="Cube 15"
              geometry={nodes["Cube 15"].geometry}
              material={materials["white-2"]}
              castShadow
              receiveShadow
              position={[22.84, 93.98, -0.5]}
              rotation={[0, 0, -0.17]}
              scale={[1, 1, 1.36]}
            />
            <mesh
              name="Cube 14"
              geometry={nodes["Cube 14"].geometry}
              material={materials["white-2"]}
              castShadow
              receiveShadow
              position={[-20.62, 96.82, -0.5]}
              scale={[1, 1, 1.36]}
            />
            <mesh
              name="Cube 5"
              geometry={nodes["Cube 5"].geometry}
              material={materials.pink}
              castShadow
              receiveShadow
              position={[-33.74, 33.29, 28.45]}
            />
            <mesh
              name="Rectangle 7"
              geometry={nodes["Rectangle 7"].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[20.9, 55.51, 35.4]}
            />
            <mesh
              name="Rectangle 11"
              geometry={nodes["Rectangle 11"].geometry}
              material={materials.red}
              castShadow
              receiveShadow
              position={[1.75, 37.23, 35.4]}
            />
            <mesh
              name="Rectangle 10"
              geometry={nodes["Rectangle 10"].geometry}
              material={materials.red}
              castShadow
              receiveShadow
              position={[1.75, 43.15, 35.4]}
            />
            <mesh
              name="Rectangle 61"
              geometry={nodes["Rectangle 61"].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[-20.44, 55.51, 35.4]}
            />
            <mesh
              name="Cube 2"
              geometry={nodes["Cube 2"].geometry}
              material={materials["white-2"]}
              castShadow
              receiveShadow
              position={[-0.11, 42.84, -5.1]}
            />
          </group>
          <mesh
            name="photo_new-min.JPG"
            geometry={nodes["photo_new-min.JPG"].geometry}
            material={materials["photo_new-min.JPG Material"]}
            castShadow
            receiveShadow
            position={[-378.19, 259.03, 1128.4]}
            scale={[1, 1, 10.04]}
          />
          <mesh
            name="Cube 3"
            geometry={nodes["Cube 3"].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-439.09, 262.02, 1099.97]}
            scale={[1, 0.97, 0.18]}
          />
          <group
            name="Desert_01"
            position={[867.95, 136.44, 908.82]}
            rotation={[0, -0.56, 0]}
            scale={0.65}
          >
            <mesh
              name="floor"
              geometry={nodes.floor.geometry}
              material={materials.sand}
              castShadow
              receiveShadow
              position={[-102.61, -0.31, -214.14]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.93}
            />
            <mesh
              name="cactus-3"
              geometry={nodes["cactus-3"].geometry}
              material={materials["plant-sphere"]}
              castShadow
              receiveShadow
              position={[140.27, 49.4, 51]}
              rotation={[1.69, 1.21, -1.62]}
              scale={0.93}
            />
            <group
              name="cactus-1"
              position={[148.96, 30.56, 75.58]}
              rotation={[0.03, 0.7, -0.13]}
              scale={0.82}
            >
              <mesh
                name="cactus-11"
                geometry={nodes["cactus-11"].geometry}
                material={materials.plant}
                castShadow
                receiveShadow
                position={[-7.82, 18.62, -45.61]}
                rotation={[0.07, -0.7, 0.14]}
                scale={1.14}
              />
              <mesh
                name="Cylinder 6"
                geometry={nodes["Cylinder 6"].geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[-73.76, 16.03, -46.58]}
                rotation={[-2.92, 1.19, 2.68]}
                scale={0.65}
              />
              <mesh
                name="Cylinder 5"
                geometry={nodes["Cylinder 5"].geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[-62.62, 7.96, -31.09]}
                rotation={[-3.13, 1.3, -1.94]}
                scale={0.65}
              />
              <mesh
                name="Cylinder 4"
                geometry={nodes["Cylinder 4"].geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[-69.82, 15.07, -33.08]}
                rotation={[-2.46, 1.15, 2.85]}
                scale={0.65}
              />
            </group>
            <mesh
              name="cactus"
              geometry={nodes.cactus.geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-193.66, 168.54, -28.55]}
              scale={0.93}
            />
            <mesh
              name="stone"
              geometry={nodes.stone.geometry}
              material={materials.stone}
              castShadow
              receiveShadow
              position={[94.58, 85, -78.43]}
              rotation={[0, 1.44, 0]}
              scale={1.07}
            />
          </group>
          <group
            name="Desert_03"
            position={[-82.72, 159, -115]}
            scale={[1, 0.86, 1]}
          >
            <mesh
              name="cactus-12"
              geometry={nodes["cactus-12"].geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[-129.87, 77.46, 207.43]}
            />
            <mesh
              name="mine"
              geometry={nodes.mine.geometry}
              material={materials.mine}
              castShadow
              receiveShadow
              position={[-7.04, 8.14, 179.36]}
            />
            <mesh
              name="wood"
              geometry={nodes.wood.geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[16.61, 51.43, 181.03]}
            />
            <mesh
              name="cactus-2"
              geometry={nodes["cactus-2"].geometry}
              material={materials.plant}
              castShadow
              receiveShadow
              position={[297.34, 74.13, 38.74]}
            />
            <mesh
              name="rock"
              geometry={nodes.rock.geometry}
              material={materials.stone}
              castShadow
              receiveShadow
              position={[146.94, 95.08, -17.75]}
              rotation={[0, -0.55, 0]}
              scale={0.71}
            />
            <mesh
              name="floor1"
              geometry={nodes.floor1.geometry}
              material={materials.sand}
              castShadow
              receiveShadow
              position={[-173.27, -51.85, -131.74]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.62}
            />
          </group>
          <mesh
            name="Cube 51"
            geometry={nodes["Cube 51"].geometry}
            material={materials[""]}
            castShadow
            receiveShadow
            position={[-501.01, 180.53, 1099.97]}
            rotation={[0, -1.56, 0]}
            scale={[1, 1, 1.03]}
          />
          <mesh
            name="Cube 21"
            geometry={nodes["Cube 21"].geometry}
            material={materials[""]}
            castShadow
            receiveShadow
            position={[-376.21, 187.67, 1099.97]}
            rotation={[0, -1.56, 0]}
            scale={[1, 1, 1.03]}
          />
          <mesh
            name="Cube 61"
            geometry={nodes["Cube 61"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[197.3, 126.75, 609.02]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[22.42, 1, 1]}
          />
          <group
            name="Group"
            position={[410.29, 306.98, 119.75]}
            rotation={[0, 0.38, 0]}
            scale={1}
          >
            <mesh
              name="Sphere 4"
              geometry={nodes["Sphere 4"].geometry}
              material={materials["Sphere 4 Material"]}
              castShadow
              receiveShadow
              position={[27.24, 14.68, 39.89]}
              rotation={[0, 0.62, 0]}
            />
            <mesh
              name="Sphere 3"
              geometry={nodes["Sphere 3"].geometry}
              material={materials["Sphere 3 Material"]}
              castShadow
              receiveShadow
              position={[-20.76, 15.68, 41.89]}
              rotation={[0, 0.62, 0]}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials["Sphere Material"]}
              castShadow
              receiveShadow
              position={[0, 0, -6.45]}
            />
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[1091.19, 901.83, -806.86]}
            rotation={[-1.49, 0.19, Math.PI]}
            scale={[1.29, 1.27, 1.47]}
          />
          <OrthographicCamera
            name="1"
            makeDefault={true}
            far={10000}
            near={-50000}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={1.36}
            color="#eaeaea"
          />
        </scene>
      </group>
    </>
  );
}
